config/routes.rb
HciPrototype::Application.routes.draw do

  match 'email' => 'dashboard#email_main'
  match 'projects' => 'dashboard#projects_main'
  match 'alternative_projects' => 'dashboard#alternative_projects'
  match 'contacts' => 'dashboard#contacts_main'
  match 'calendar' => 'dashboard#calendar_main'
  match 'chat' => 'dashboard#send_chat'
  match 'search/:query' => 'dashboard#search'

  root :to => 'dashboard#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def email_main
  end

  def projects_main
  end

  def contacts_main
  end

  def calendar_main
  end

  def send_chat
    render :json => ''
  end

  def search
  end

  def alternative_projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/alternative_projects.html.erb
<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header">
			<h2><i class="icon-tasks"></i><span class="break"></span>Projects & Tasks</h2>&nbsp;&nbsp;&nbsp;
		</div>
		<div class="box-content">
			<div class="gantt"></div>
		</div>
	</div><!--/span-->

</div><!--/row-->

<div class="row-fluid sortable">

	<div class="box span12">
		<div id="open-task" class="modal" style="position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width: 100%;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		    <h3 id="myModalLabel">Task Description</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				Project: <strong><div id="open-task-project"></div></strong>
				<h6></small>Progress</h6>
				<div class="progress progress-striped progress-information active"><div id="progress_bar" class="bar" style="width: 0;"></div></div>
			  </div>
			  <div class="control-group">
				Due Date: <strong><div id="open-task-date"></div></strong>
			  </div>
			  <div class="control-group">
				Task: <strong><span id="open-task-name"></span></strong> <span id="open-task-status"></span>
			  </div>
			<div class="control-group hidden-phone">
			  <div class="controls">
				<div id="open-task-description"><div style="text-align:center"><%= image_tag 'avatar.jpg', :alt => 'HCI Prototype Dashboard' %><h1>Please select a Task.</h1></div></div>
			  </div>
			</div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    &nbsp;
		  </div>
		</div>
	</div><!--/span-->
</div><!--/row-->

<!-- start: JavaScript-->
<script type="text/javascript" language="JavaScript">

$(document).ready(function(){

	$(".gantt").gantt({
		source: [{
			name: "Sales Project",
			desc: "Build Sales Pipeline",
			values: [{
				from: "/Date("+Date.parse("2012-11-08").add(-1).days().getTime()+")/",
				to: "/Date("+Date.parse("2012-11-12").add(-1).days().getTime()+")/",
				label: "Requirement Gathering",
				customClass: "ganttRed"
			}]
		},{
			name: " ",
			desc: "Scoping",
			values: [{
				from: "/Date(1322611200000)/",
				to: "/Date(1323302400000)/",
				label: "Scoping",
				customClass: "ganttRed"
			}]
		},{
			name: "Hotfixes",
			desc: "Fix Main Dashboard",
			values: [{
				from: "/Date(1323802400000)/",
				to: "/Date(1325685200000)/",
				label: "Development",
				customClass: "ganttGreen"
			}]
		},{
			name: " ",
			desc: "Showcasing",
			values: [{
				from: "/Date(1325685200000)/",
				to: "/Date(1325695200000)/",
				label: "Showcasing",
				customClass: "ganttBlue"
			}]
		},{
			name: "Invoice Software v0.6",
			desc: "Development",
			values: [{
				from: "/Date(1326785200000)/",
				to: "/Date(1325785200000)/",
				label: "Development",
				customClass: "ganttGreen"
			}]
		},{
			name: " ",
			desc: "Showcasing",
			values: [{
				from: "/Date(1328785200000)/",
				to: "/Date(1328905200000)/",
				label: "Showcasing",
				customClass: "ganttBlue"
			}]
		},{
			name: "New Arrivals",
			desc: "Training",
			values: [{
				from: "/Date(1330011200000)/",
				to: "/Date(1336611200000)/",
				label: "Training",
				customClass: "ganttOrange"
			}]
		},{
			name: " ",
			desc: "Deployment",
			values: [{
				from: "/Date(1336611200000)/",
				to: "/Date(1338711200000)/",
				label: "Deployment",
				customClass: "ganttOrange"
			}]
		}],
		navigate: "scroll",
		scale: "weeks",
		maxScale: "months",
		minScale: "days",
		itemsPerPage: 10,
		onItemClick: function(data) {
			$('#open-task-project').text('Sales Project');
			$('#open-task-name').text('Gather Requirements');
			$('#open-task-date').text('2012-10-11');
			$('#open-task-description').lorem({type: 'paragraphs', amount:'1', ptags:true});

			$('#progress_bar').css('width', Math.floor(Math.random()*101) + '%');
		},
		onAddClick: function(dt, rowId) {
			alert("Empty space clicked - on a next prototype a Task will be added!");
		},
		onRender: function() {
			if (window.console && typeof console.log === "function") {
				console.log("chart rendered");
			}
		}
	});

});
</script>
<!-- end: JavaScript-->

app/views/dashboard/calendar_main.html.erb
<div class="row-fluid">

	<div class="box span9">
		<div class="box-header">
			<h2><i class="icon-calendar"></i><span class="break"></span>Calendar</h2> &nbsp;&nbsp;&nbsp;<button class="btn btn-mini btn-create-event" data-toggle="modal" data-target="#create-event">New Event</button>
		</div>
		<div class="box-content">
			<div id="main_calendar" class="hidden-phone"></div>
			<div id="main_calendar_phone" class="hidden-desktop hidden-tablet"></div>
			<div class="clearfix"></div>
		</div>
	</div><!--/span-->

	<div class="box span3">
		<input type="hidden" id="current_event_id" value="" />
		<div id="open-event" class="modal" style="position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; max-width: 100%;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-danger delete-event hidden" data-dismiss="modal" aria-hidden="true">Delete</button></div>
		    <h3 id="myModalLabel">Event Details</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				Title: <strong><div id="open-event-title"></div></strong>
			  </div>
			  <div class="control-group">
				Start Date: <strong><div id="open-event-start-date"></div></strong>
			  </div>
			  <div class="control-group">
				End Date: <strong><div id="open-event-end-date"></div></strong>
			  </div>
			<div class="control-group hidden-phone">
			  <div class="controls">
				<div id="open-event-description"><div style="text-align:center"><%= image_tag 'avatar.jpg', :alt => 'HCI Prototype Dashboard' %><h1>Please select an Event.</h1></div></div>
			  </div>
			</div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		  </div>
		</div>
	</div><!--/span-->
</div>

<!-- start: JavaScript-->
<script type="text/javascript" language="JavaScript">
function message_tip1(){
	var unique_id = $.gritter.add({
		// (string | mandatory) the heading of the notification
		title: 'Calendar tips',
		// (string | mandatory) the text inside the notification
		text: 'Click on an Event to see details.',
		// (string | optional) the image to display on the left
		image: "<%= asset_path 'avatar.jpg' %>",
		// (bool | optional) if you want it to fade out on its own or just sit there
		sticky: false,
		// (int | optional) the time you want it to be alive for before fading out
		time: 8000,
		// (string | optional) the class name you want to apply to that specific message
		class_name: 'gritter-light'
	});
}

$(document).ready(function(){

	setTimeout("message_tip1()", 5000);

});
</script>
<!-- end: JavaScript-->

app/views/dashboard/contacts_main.html.erb
<div class="row-fluid">

	<div class="box span3">
		<div class="box-header">
			<h2><i class="icon-user"></i><span class="break"></span>Contacts</h2>
			<div class="box-icon">
				<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
				<a href="#" class="btn-close"><i class="icon-remove"></i></a>
			</div>
		</div>
		<div class="box-content">
			<label class="control-label" for="selectError">Last name starts with...</label>
			<div class="controls">
			  <select id="contacts_filter">
			  	<option value="">Select to filter...</option>
				<option value="A">A</option>
				<option value="B">B</option>
				<option value="C">C</option>
			  </select>
			</div>
			<ul class="contacts-list" style="list-style-type:none">
				<li data-last-name-initial="A" class="open-contact" data-id="1">
					<%= image_tag 'avatar_p01.png', :alt => 'Lucas', :class => 'dashboard-avatar' %>
					<strong>Name:</strong> <a href="#">Lucas A.</a><br>
					<strong>Since:</strong> 17/05/2012<br>
					<strong>Status:</strong> <span class="label label-success">Online</span>
				</li>
				<li data-last-name-initial="B" class="open-contact" data-id="2">
					<a href="#">
						<%= image_tag 'avatar_p02.png', :alt => 'Bill', :class => 'dashboard-avatar' %>
					</a>
					<strong>Name:</strong> <a href="#">Bill B.</a><br>
					<strong>Since:</strong> 17/05/2012<br>
					<strong>Status:</strong> <span class="label">Offline</span>
				</li>
				<li data-last-name-initial="C" class="open-contact" data-id="3">
					<a href="#">
						<%= image_tag 'avatar_p04.png', :alt => 'Jane', :class => 'dashboard-avatar' %>
					</a>
					<strong>Name:</strong> <a href="#">Jane C.</a><br>
					<strong>Since:</strong> 17/05/2012<br>
					<strong>Status:</strong> <span class="label">Offline</span>
				</li>
				<li data-last-name-initial="C" class="open-contact" data-id="4">
					<a href="#">
						<%= image_tag 'avatar_p03.png', :alt => 'Dexter', :class => 'dashboard-avatar' %>
					</a>
					<strong>Name:</strong> <a href="#">Dexter C.</a><br>
					<strong>Since:</strong> 17/05/2012<br>
					<strong>Status:</strong> <span class="label label-success">Online</span>
				</li>
			</ul>
		</div>
	</div><!--/span-->

	<div class="box span9">
		<input type="hidden" id="current_event_id" value="" />
		<div id="open-event" class="modal" style="position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; max-width: 100%;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-info contact-open-chat hidden" data-dismiss="modal" aria-hidden="true" onclick="">Chat</button></div>
		    <h3 id="myModalLabel">Contact Profile</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="row-fluid">
				  <div class="span4 ">
					<div class="well" style="text-align:center">
						<%= image_tag 'avatar.jpg', :id => 'contact_avatar' %>
					</div>
				  </div>
				  <div class="span8">
					  <div class="control-group">
						Name: <strong><div id="open-contact-name"></div></strong>
					  </div>
					  <div class="control-group">
						Department: <strong><div id="open-contact-dept"></div></strong>
					  </div>
					  <div class="control-group">
						Location: <strong><div id="open-contact-location"></div></strong>
					  </div>
					  <div class="control-group">
						Phone: <strong><div id="open-contact-phone"></div></strong>
					  </div>
					  <div class="control-group">
						Quote: <strong><i><div id="open-contact-quote"><div style="text-align:center"><%= image_tag 'avatar.jpg', :alt => 'HCI Prototype Dashboard' %><h1>Please select a Contact.</h1></div></div></i></strong>
					  </div>
				  </div>
			  </div><!--/row -->
		  </div>
		  <div class="modal-footer" style="text-align:left">
		  </div>
		</div>
	</div><!--/span-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>HCI Prototype Dashboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Optimus Dashboard Bootstrap Admin Template.">
  <meta name="author" content="John Doe">
  <!-- end: Meta -->

  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- start: Favicon -->
  <link rel="shortcut icon" href="favicon.ico">
  <!-- end: Favicon -->
</head>

<body>
	<input type="hidden" id="app_url" value="<%=request.fullpath%>" />
	<!-- start: Header -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%= link_to(root_url, :class => 'brand') do %>
					<%= image_tag 'logo20.png', :alt => 'HCI Prototype Dashboard' %> <span>HCI Prototype Dashboard</span>
				<% end %>
				<div class="btn-group pull-left">
				  <div class="input-append">
					<span class="add-on"><i class="icon-search"></i></span><input id="app_search_input" size="24" type="text"><button class="btn" type="button" id="app_search_button">Search</button>
				  </div>
				</div>

				<!-- start: Header Menu -->
				<div class="btn-group pull-right" >
					<a class="btn" href="#" data-toggle="modal" data-target="#open-help">
						<i class="icon-question-sign"></i><span class="hidden-phone hidden-tablet"> Help</span>
					</a>
					<a class="btn" href="#" data-toggle="modal" data-target="#open-setting">
						<i class="icon-wrench"></i><span class="hidden-phone hidden-tablet"> Settings</span>
					</a>
					<!-- start: User Dropdown -->
					<a class="btn" href="#">
						<i class="icon-heart"></i> Hello, John Doe!
					</a>
					<!-- end: User Dropdown -->
				</div>
				<!-- end: Header Menu -->

			</div>
		</div>
	</div>
	<div id="under-header"></div>
	<!-- start: Header -->
		<div class="container-fluid">
		<div class="row-fluid">

			<!-- start: Main Menu -->
			<div class="span2 main-menu-span">
				<div class="nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li class="nav-header hidden-tablet">Navigation</li>
						<li>
						<%= link_to(root_url) do %>
							<i class="icon-home"></i><span class="hidden-tablet"> Dashboard</span>
						<% end %>
						</li>
						<li>
						<%= link_to(email_url) do %>
							<i class="icon-envelope"></i><span class="hidden-tablet"> Email <span class="label label-success hidden-phone email-count">16</span></span>
						<% end %>
						</li>
						<li>
						<%= link_to(projects_url) do %>
							<i class="icon-tasks"></i><span class="hidden-tablet"> Projects</span>
						<% end %>
						</li>
						<li>
						<%= link_to(calendar_url) do %>
							<i class="icon-calendar"></i><span class="hidden-tablet"> Calendar</span>
						<% end %>
						</li>
						<li>
						<%= link_to(contacts_url) do %>
							<i class="icon-user"></i><span class="hidden-tablet"> Contacts</span>
						<% end %>
						</li>
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
			<!-- end: Main Menu -->

			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>

			<div id="content" class="span10">

<%= yield %>

			</div><!--/#content.span10-->
				</div><!--/fluid-row-->

		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>

		<!-- Modal -->
		<div id="compose-email" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">Compose Email</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				To &nbsp;&nbsp;&nbsp;<input class="input-xlarge" id="email_to" type="text" value="">
			  </div>
			  <div class="control-group">
				Cc &nbsp;&nbsp;<input class="input-xlarge" id="email_cc" type="text" value="">
			  </div>
			  <div class="control-group">
				Subject <input class="input-xlarge" id="email_subject" type="text" value="">
			  </div>
			<div class="control-group hidden-phone">
			  <label class="control-label" for="email_body">Body</label>
			  <div class="controls">
				<textarea class="cleditor" id="email_body" rows="3">Please select an Email.</textarea>
			  </div>
			</div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    <button class="btn btn-primary send-email">Send</button> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		    <a onclick="$('input[id=lefile]').click();" class="btn btn-mini btn-info" ><i class="icon-list-alt"></i> Attachment</a>
		    <input id="lefile" type="file" style="display:none;visibility:hidden">
		  </div>
		</div>

		<div id="open-email" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">Open Email</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				From: <strong><div id="open-email-from"></div></strong>
			  </div>
			  <div class="control-group">
				Date: <strong><div id="open-email-date"></div></strong>
			  </div>
			  <div class="control-group">
				Subject: <strong><div id="open-email-subject"></div></strong>
			  </div>
			<div class="control-group hidden-phone">
			  <div class="controls">
				<div id="open-email-body"></div>
			  </div>
			</div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    <button class="btn btn-primary reply-email">Reply</button>
		  </div>
		</div>

		<div id="open-task" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">Task Description</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				Project: <strong><div id="open-task-project"></div></strong>
			  </div>
			  <div class="control-group">
				Due Date: <strong><div id="open-task-date"></div></strong>
			  </div>
			  <div class="control-group">
				Task: <strong><span id="open-task-name"></span></strong> <span id="open-task-status"></span>
			  </div>
			<div class="control-group hidden-phone">
			  <div class="controls">
				<div id="open-task-description"></div>
			  </div>
			</div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    &nbsp;
		  </div>
		</div>

		<div id="create-task" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">New Task</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				Project &nbsp;&nbsp;&nbsp;
				<select id="task_project">
				<option value="">Select an option...</option>
				<option value="Sales Project">Sales Project</option>
				<option value="Hotfixes">Hotfixes</option>
				<option value="Client Leads">Client Leads</option>
				<option value="Email Software v3.4">Email Software v3.4</option>
			  </select>
			  </div>
			  <div class="control-group">
				Due Date &nbsp;&nbsp;&nbsp;&nbsp;<input class="input-xlarge datepicker" id="task_date" type="text" value="">
			  </div>
			  <div class="control-group">
				Task &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input class="input-xlarge" id="task_name" type="text" value="">
			  </div>
			<div class="control-group hidden-phone">
			  <label class="control-label" for="email_body">Description</label>
			  <div class="controls">
				<textarea id="task_description" rows="5" cols="30" style="width: 500px"></textarea>
			  </div>
			</div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    <button class="btn btn-primary new-task">Create</button>
		  </div>
		</div>

		<div id="create-event" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">New Event</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				Title &nbsp;&nbsp;&nbsp;&nbsp;<input class="input-xlarge" id="event_title" type="text" value="">
			  </div>
			  <div class="control-group">
				Start Date &nbsp;&nbsp;&nbsp;&nbsp;<input class="datepicker" id="event_start_date" type="text" value="">
			  </div>
			  <div class="control-group">
				End Date &nbsp;&nbsp;&nbsp;&nbsp;<input class="datepicker" id="event_end_date" type="text" value="">
			  </div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    <button class="btn btn-primary new-event">Create</button>
		  </div>
		</div>


		<div id="open-setting" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">Settings</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <div class="control-group">
				Do you want to receive an Email every time you get a new Task? &nbsp;&nbsp;&nbsp;&nbsp;<select><option>Yes</option><option>No</option></select>
			  </div>
			  <div class="control-group">
				Do you want to receive a Notification when an Event is Due? &nbsp;&nbsp;&nbsp;&nbsp;<select><option>Yes</option><option>No</option></select>
			  </div>
			  <div class="control-group">
				Do you want to authorize people before chatting with you? &nbsp;&nbsp;&nbsp;&nbsp;<select><option>Yes</option><option>No</option></select>
			  </div>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		    <button class="btn btn-primary save-setting">Save</button>
		  </div>
		</div>

		<div id="open-help" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		  	<div style="float:right"><button type="button" class="btn btn-mini btn-warning" data-dismiss="modal" aria-hidden="true">Close</button></div>
		    <h3 id="myModalLabel">Help</h3>
		  </div>
		  <div class="modal-body" style="max-height: 530px">
			  <h1>Welcome to the HCI Prototype Dashboard!</h1>
			  <p>This <strong>Dashboard</strong> allows you to see at glance all you Email, Tasks, Calendar Events and Contacts.</p>

<p>Please, use the <strong>Navigation</strong> to you left to access all sections in detail.</p>

<p>In the <strong>Email</strong> section, you may read your email, compose email, send replies and archive or delete you email.</p>

<p>In the <strong>Projects</strong> section, you may see your assigned Task, the progress on their Projects and Mark your tasks as Done.</p>

<p>In the <strong>Calendar</strong> section, you may see your scheduled events at glance (Agenda, Monthly, Yearly), create new Events or delete them.</p>

<p>In the <strong>Contacts</strong> section, you may browse the your company directory, see a Contact information or invite to Chat those who are online.</p>

<p>Finally, you may perform a <strong>Global Search</strong> with the input on the header.</p>

<p><strong>Have fun and thanks for your time. :)</strong></p>
</p>
		  </div>
		  <div class="modal-footer" style="text-align:left">
		  </div>
		</div>

		<div class="clearfix"></div>
		<hr>

		<footer>
			<p class="pull-left"><a href="" target="_blank">Coursera HCI Class</a> 2012</p>
			<p class="pull-right">Powered by: <a href="#">Twitter Bootstrap</a></p>
		</footer>

	</div><!--/.fluid-container-->
</body>
</html>